### ISSUE TITLE
RuntimeError: ERROR: Serial protocol mismatch

### ISSUE THREAD

**Issue by fossie08** [Dragon863/EchoCLI#25]
Hi there!

I thought I had fixed my earlier error, that's why I closed the issue but I have tried on 2 different echos and 4 different machines (1x Windows 11 and 3x Debian) to no success and now I'm getting this error

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ollie\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\__main__.py", line 3, in <module>
    amonet.main()
  File "C:\Users\ollie\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\__init__.py", line 215, in main
    load_payload(dev, "brom-payload/build/payload.bin")
  File "C:\Users\ollie\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\load_payload.py", line 85, in load_payload
    init(dev)
  File "C:\Users\ollie\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\load_payload.py", line 9, in init
    dev.write32(CRYPTO_BASE + 0x0C0C, 0)
  File "C:\Users\ollie\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\common.py", line 139, in write32
    self.check(self.dev.read(1), b'\xd4') # echo cmd
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollie\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\common.py", line 84, in check
    raise RuntimeError("ERROR: Serial protocol mismatch")
RuntimeError: ERROR: Serial protocol mismatch

This error appears sometimes on different OSes
Sometimes I am getting the infinite Disable Watchdog error on all the machines.

Any help is deeply appreciated. 
Thanks!

**Comment by Dragon863** [comment]
This usually occurs when the short is not in the correct place. The exiting after "check gpt" is new behavior, but could just be down to the echo not booting properly anyway. If you're sure that the short is placed correctly and you still get the error on your working echo, please let me know

**Comment by fossie08** [comment]
Hi, thanks for the help. I think I've managed to get past the mktclient section but now stuck with another error when trying to setup the home assistant led indicator.

Select an option: > 4
[19:36:13] INFO: Please edit the URL in the file shell/led.sh to your home assistant instance. Press enter to proceed...
>
[19:36:16] INFO: Waiting for booted device to be connected...
sh: 1: adb: Exec format error
[19:36:16] INFO: Booted device connected. Pushing home assistant shell script...
sh: 1: adb: Exec format error
[19:36:16] FAIL: Command failed. Exiting...
Command fail

this is all happening whilst the working echo is connected. Are there any other instructions that I'm missing?

**Comment by Dragon863** [comment]
Is your echo successfully rooted and detected by `adb devices`? If so it will just be adb misunderstanding the arguments provided to it, as different versions work differently (or if you're using windows it interprets paths in another way). You can try running the commands manually, they are found in `internal/home assistant.py`.

**Comment by fossie08** [comment]
I ended up using a raspberry pi running pi os. Here is the output from adb devices. I did get the green ring

-bash: /home/pi/alexa/platform-tools/adb: cannot execute binary file: Exec format error

**Comment by Dragon863** [comment]
Ah okay, that's not an issue with any of my code, but from running an x86 build of adb on an arm processor (the pi).

**Comment by fossie08** [comment]
I've now swapped to a machine with an Intel processor running Debian and ran through the process again. Got the green ring etc but still have no idea to go after that. adb devices isn't showing anything either

**Comment by rocks860** [comment]
> I've now swapped to a machine with an Intel processor running Debian and ran through the process again. Got the green ring etc but still have no idea to go after that. adb devices isn't showing anything either

Did you get anything done after green light? Mine is not recognized by adb devices.  I am think I am missing some steps.

**Comment by tails1154** [comment]
@rocks860  fastboot devices
