### ISSUE TITLE
ready, but

### ISSUE THREAD

**Issue by FamousL** [Dragon863/EchoCLI#27]
Hello, 

Was trying to root a 2nd gen, and not quite sure what I managed to miss.

Select an option: > 1
[11:51:10] INFO: Please short the device as shown in the image at https://danieldb.uk/posts/alexa-1/mainboard.jpg
[11:51:10] INFO: To open the device, you will need a torx 8 screwdriver.
[11:51:10] Waiting for bootrom
[11:51:20] Found port = /dev/ttyACM0
[11:51:20] Handshake
Traceback (most recent call last):
  File "/home/famous/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/famous/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/famous/build/EchoCLI/internal/amonet/amonet/__main__.py", line 3, in <module>
    amonet.main()
  File "/home/famous/build/EchoCLI/internal/amonet/amonet/__init__.py", line 207, in main
    handshake(dev)
  File "/home/famous/build/EchoCLI/internal/amonet/amonet/handshake.py", line 9, in handshake
    dev.handshake()
  File "/home/famous/build/EchoCLI/internal/amonet/amonet/common.py", line 97, in handshake
    c = self._writeb(b'\xa0')
  File "/home/famous/build/EchoCLI/internal/amonet/amonet/common.py", line 92, in _writeb
    return self.dev.read()
  File "/home/famous/.local/lib/python3.10/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

I am reasonably certain nothing else is using this port.

**Comment by FamousL** [comment]
heh bad cable...
